repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version. Keep in sync with pyproject.toml and .gitlab-ci.yml.
  rev: v0.16.0
  hooks:
    - id: ruff-format
      types_or: [ python, pyi ]
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]