[tool.ruff]
line-length = 88
exclude = ["*.ipynb"]

[tool.poetry]
name = "ufz-flask"
version = "0.1.0"
description = "This is Poetry"
authors = ["Louis Ferdinand Trinkle <louis-ferdinand.trinkle@ufz.de>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "3.12.0"
blinker = "1.6.2"
click = "8.1.7"
flask = "2.3.3"
flask-wtf = "1.1.1"
itsdangerous = "2.1.2"
jinja2 = "3.1.2"
markupsafe = "2.1.3"
Werkzeug = "2.3.7"
WTForms = "3.0.1"
flask-bootstrap = "^3.3.7.1"
bootstrap-flask = "^2.3.2"
pyproj = "^3.6.1"
shapely = "^2.0.2"
geojson = "^3.0.1"
pandas = "^2.1.2"
plotly = "^5.18.0"
dash = "^2.14.1"
geopandas = "^0.14.1"
dash-leaflet = "^1.0.11"
pydantic = "^2.5.3"
matplotlib = "^3.8.2"
numpy = "^1.26.4"
ipykernel = "^6.29.0"
osmnx = "^1.9.1"
gdal = "3.3.0"
rasterio = "^1.3.9"
minio = "^7.2.5"
python-dotenv = "^1.0.1"
qrcode = {extras = ["pil"], version = "^7.4.2"}
gpxpy = "^1.6.2"
dash-bootstrap-components = "^1.6.0"
dash-extensions = "^1.0.15"
sqlalchemy = "^2.0.30"
psycopg2 = "^2.9.9"
gunicorn = "^22.0.0"
networkx = "^3.3"
ruff = "^0.7.3"
pre-commit = "^4.0.1"
sensor-routing = "^0.1"
celery = "^5.4.0"
redis = "^5.2.1"

[tool.poetry.group.dev.dependencies]
blinker = "1.6.2"
click = "8.1.7"
flask = "2.3.3"
flask-wtf = "1.1.1"
itsdangerous = "2.1.2"
jinja2 = "3.1.2"
markupsafe = "2.1.3"
Werkzeug = "2.3.7"
WTForms = "3.0.1"
flask-bootstrap = "^3.3.7.1"
bootstrap-flask = "^2.3.2"

[tool.poetry.group.test.dependencies]
pytest = "6.2.5"
pytest-mock = "3.6.1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
