"""Documentation page displaying auto-generated user and administrator guides.

This page provides comprehensive documentation for the COSMONAUT application,
including detailed instructions for each step of the routing workflow and
guidance for administrative features.

The documentation content is automatically generated by the `doc_generator.py`
module, which:
1. Extracts module-level docstrings from each page module
2. Captures screenshots of each page using Playwright browser automation
3. Compiles everything into a structured Markdown document
4. Saves the output to `assets/docs/documentation.md`

The generated documentation includes:

**User Workflow Pages** (7 sequential steps):
- Home: Creating new routing jobs
- User Info: Email address entry and validation
- Data Upload: CSV membership file upload and EPSG configuration
- Street Selection: Interactive OpenStreetMap data selection and filtering
- Routing Parameters: Route optimization configuration
- Route Computation: Background job execution and monitoring
- Route Download: GPX file download and QR code sharing

**Administrative Pages** (3 management interfaces):
- Logs: Application log viewer with filtering and search
- Worker Management: Celery worker monitoring and task management
- Job Manager: Job lifecycle management and database cleanup

Each page section in the documentation includes:
- Descriptive text extracted from the page module's docstring
- An embedded screenshot showing the page interface with realistic data
- Step-by-step instructions and feature descriptions

The documentation is version-tracked using `doc_version.txt`, which reads the
application version from `pyproject.toml` to ensure documentation and code
stay synchronized.

**Generating Updated Documentation:**
Documentation is regenerated manually via CLI when page content changes:

```bash
python -m cosmonaut_app.doc_generator <job_id> [--no-headless]
```

Requirements:
- Development server running at http://localhost:8080
- A completed job_id with data through all workflow steps
- Playwright browser automation dependencies installed

NOTE: Documentation is generated as a pre-deployment step, not at runtime.
If the documentation files don't exist, this page will display an error
message with instructions for generating them.
"""

from pathlib import Path

import dash_bootstrap_components as dbc
from dash import dcc, register_page

from cosmonaut_app.layout import (
    create_header,
    page_container_column_layout,
)

register_page(
    __name__,
    path="/documentation",
    name="Documentation",
    title="COSMONAUT - Documentation",
    description="User and administrator documentation for COSMONAUT.",
)


docs_dir = Path(__file__).parent.parent / "assets" / "docs"
docs_file = docs_dir / "documentation.md"

documentation_markdown = docs_file.read_text(encoding="utf-8")

header = create_header(
    "Documentation",
    "User guide and reference for the COSMONAUT webservice",
    bg_color="bg-info",
)

# Markdown content with HTML support for anchor links
markdown_content = dcc.Markdown(
    documentation_markdown,
    dangerously_allow_html=True,
)

# Layout
layout = page_container_column_layout(
    [
        header,
        dbc.Row(dbc.Col(markdown_content, className="col-11 col-xl-10 mx-auto my-4")),
    ]
)
